[build]
rustflags = [
    "-C", "target-feature=+crt-static",
    "-C", "prefer-dynamic=no",
    "-C", "embed-bitcode=no",
]

# Linux x86_64 - targets CPUs from ~2009+
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-cpu=x86-64-v2",
    "-C", "target-feature=+crt-static",
    "-C", "link-arg=-s",
]

# Windows x86_64 - targets CPUs from ~2009+
[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-cpu=x86-64-v2",
    "-C", "target-feature=+crt-static",
]

# macOS Intel - baseline x86_64 for compatibility
[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-dead_strip",
    "-C", "link-arg=-dead_strip_dylibs",
]

# macOS Apple Silicon - all M1/M2/M3+ chips
[target.aarch64-apple-darwin]
rustflags = [
    "-C", "target-cpu=apple-m1",
    "-C", "link-arg=-dead_strip",
    "-C", "link-arg=-dead_strip_dylibs",
]